name: Install ghactl
description: Installs GitHub Actions CLI (`ghactl`).
branding:
  icon: zap
  color: yellow
inputs:
  token:
    description: GitHub token to use for authentication.
    required: true
    default: ${{ github.token }}
  version:
    description: Version of `ghactl` to install; defaults to `latest`.
    required: false
    default: latest
runs:
  using: composite
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      with:
        cosign-release: v3.1.1

    - name: Install ghactl
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        INPUT_VERSION: ${{ inputs.version }}
      run: |
        set -euo pipefail

        echo "::group::Bootstrapping ghactl"

        version="${INPUT_VERSION}"
        if [[ "${version}" == "latest" ]]; then
          version="$(curl --silent --show-error --fail --location --header "Authorization: Bearer ${GITHUB_TOKEN}" "https://api.github.com/repos/action-stars/ghactl/releases/latest" | jq --raw-output '.tag_name')"
        fi
        version="${version#v}"
        echo "Bootstrap version: ${version}"

        case "${RUNNER_OS}" in
          Linux)
            os="linux"
            ;;
          macOS)
            os="darwin"
            ;;
          Windows)
            os="windows"
            ;;
          *)
            echo "::error::Unsupported runner OS ${RUNNER_OS}"
            exit 1
            ;;
        esac
        echo "Bootstrap OS: ${os}"

        case "${RUNNER_ARCH}" in
          X64)
            arch="amd64"
            ;;
          ARM64)
            arch="arm64"
            ;;
          *)
            echo "::error::Unsupported runner architecture ${RUNNER_ARCH}"
            exit 1
            ;;
        esac
        echo "Bootstrap architecture: ${arch}"

        temp_dir="$(mktemp -d)"

        checksums_path="${temp_dir}/checksums.txt"
        checksum_url="https://github.com/action-stars/ghactl/releases/download/v${version}/checksums.txt"
        curl --silent --show-error --fail --location --header "Authorization: Bearer ${GITHUB_TOKEN}" --output "${checksums_path}" "${checksum_url}"

        bundle_path="${temp_dir}/checksums.txt.sbom.json.bundle"
        bundle_url="https://github.com/action-stars/ghactl/releases/download/v${version}/checksums.txt.sbom.json.bundle"
        curl --silent --show-error --fail --location --header "Authorization: Bearer ${GITHUB_TOKEN}" --output "${bundle_path}" "${bundle_url}"

        archive_path="${temp_dir}/ghactl_${version}_${os}_${arch}.tar.gz"
        archive_url="https://github.com/action-stars/ghactl/releases/download/v${version}/ghactl_${version}_${os}_${arch}.tar.gz"
        curl --silent --show-error --fail --location --header "Authorization: Bearer ${GITHUB_TOKEN}" --output "${archive_path}" "${archive_url}"
        echo "Bootstrap archive: ${archive_path}"

        echo "Verifying bootstrap archive"

        cosign verify-blob \
          --bundle "${bundle_path}" \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \
          --certificate-identity "https://github.com/action-stars/ghactl/.github/workflows/release.yaml@refs/tags/v${version}" \
          "${checksums_path}"

        pushd "${temp_dir}" >/dev/null
        shasum --algorithm 256 --check "${checksums_path}" --ignore-missing
        popd >/dev/null

        tar -xzf "${archive_path}" --directory "${temp_dir}"

        if [[ "${RUNNER_OS}" == "Windows" ]]; then
          ghactl_cmd="${temp_dir}/ghactl.exe"
        else
          ghactl_cmd="${temp_dir}/ghactl"
        fi
        echo "Bootstrap command: ${ghactl_cmd}"

        echo "::endgroup::"

        echo "::group::Installing ghactl"

        path="$("${ghactl_cmd}" tool install --owner action-stars --repo ghactl --version "${version}")"
        echo "Version: ${version}"
        echo "Path: ${path}"

        echo "::endgroup::"
